/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2025-2026 Fraser Heavy Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef BLOCK_H_INCLUDED
#define BLOCK_H_INCLUDED

#include "libo-table.h"

struct block_t;
struct instruction_t;
struct location_t;
struct otable_t;
struct string_t;
struct vector_t;

typedef struct block_t {
    table_entry_t entry;
    struct location_t* location;
    struct string_t* name;

    // The list of instructions. Upon parsing the input, the last instruction
    // must be a block end instruction (ret, jmp, br), and no other
    // instructions can be block ends. The instructions are then transformed in
    // place into assembly.
    struct vector_t* instructions;

    // A marker to tell whether a transformation pass has visited this block.
    int visited;

    // List of blocks that jump/branch to this one. See analyze_block_parents().
    struct vector_t* parent_blocks;

    // Table of possibly live temporaries at the end of the block, generated by
    // liveness analysis and used for register allocation.
    struct otable_t* live_temps;
} block_t;

/**
 * Creates a block.
 *
 * Takes ownership of location.
 */
block_t* block_new(const char* name, struct location_t* location);

void block_delete(block_t* block);

void blocks_setup(void);
void blocks_teardown(void);

/**
 * Clears the blocks table.
 */
void blocks_clear(void);

/**
 * Finds a block by name (label.)
 *
 * Raises a fatal error if the block is not found.
 */
struct block_t* block_find(const struct string_t* name);

#endif
