/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2025 Fraser Heavy Software
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef OPTIMIZE_H_INCLUDED
#define OPTIMIZE_H_INCLUDED

/*
 * This file contains the various optimization passes.
 *
 * An optimization pass walks through the `instructions` array (see
 * instruction.h) and manipulates it in place. Each pass is independent and
 * self-contained; it takes in valid assembly and it must leave the array as
 * valid assembly with observable behaviour unchanged.
 */

#include <stdbool.h>

#include "register.h"



/*
 * Stack push/pop elimination
 *
 * This replaces push/pop pairs with movs into unused registers. For example,
 * cci/0 emits huge amounts of push/pop instructions like this:
 *
 *     push r0
 *     ...
 *     push r0
 *     ...
 *     pop r1
 *     ...
 *     pop r1
 *
 * This optimization pass converts the above to:
 *
 *     mov r5 r0
 *     ...
 *     mov r4 r0
 *     ...
 *     mov r1 r4
 *     ...
 *     mov r1 r5
 *
 * The optimization is done in a single pass through the function. It only
 * applies if there are no labels, jumps or calls (things that mess with
 * registers or the stack) in between the push and pop.
 *
 * This hopefully increases performance significantly on its own; push/pop are
 * two primitive instructions that touch memory while mov is one primitive
 * instruction that uses only registers. More importantly, this prepares for
 * other transformations that will rename registers and eliminate more code.
 *
 * This uses the extra fields in `instruction_t` to store a stack of push
 * instructions. The `opt_vp` field stores the stack of push instructions as an
 * intrusive linked list. The `opt_int` field stores the lowest numbered
 * register that can be used by a push/pop pair.
 *
 * Registers r4-r9 are not used in cci/0 assembly (except r9 in the function
 * preamble) so we use them to replace push/pop. This lets us replace up to six
 * nested push/pop so we can optimize some pretty deep expressions. This code
 * only works on the subset of assembly generated by cci/0, not on handwritten
 * assembly or assembly generated by the final stage compiler. There is no
 * safety check for this.
 *
 * Note that we don't bother to optimize things like `popd` since cci/0 doesn't
 * emit those. We avoid generic optimizations in general; the transformations
 * are highly tailored to cci/0's output.
 */

static bool optimize_push_pop_blocked(opcode_t opcode) {
    // These instructions either do not preserve registers or require us to
    // preserve the stack. If any of these are encountered, we block any
    // optimizations that might cross it by discarding our push stack.
    if (opcode == OP_DECLARATION) {return true;}
    if (opcode == OP_CALL) {return true;}
    if (opcode == OP_RET) {return true;}
    if (opcode == OP_JZ) {return true;}
    if (opcode == OP_JNZ) {return true;}
    if (opcode == OP_JMP) {return true;}
    if (opcode == OP_POPD) {return true;} // TODO we probably should just not support popd at all
    return false;
}

static void optimize_push_pop(void) {
    instruction_t* last_push = NULL;

    size_t i = 0;
    while (i < instructions_count) {
        instruction_t* ins = *(instructions + i);
        opcode_t opcode = instruction_opcode(ins);
        i = (i + 1);

        // On a new block, a jump, or a function call (which quashes registers)
        // we clear the push stack.
        if (optimize_push_pop_blocked(opcode)) {
            last_push = NULL;
            continue;
        }

        // On a push, insert the instruction to the front of the stack.
        if (opcode == OP_PUSH) {
            instruction_set_opt_vp(ins, last_push);
            last_push = ins;
            // We don't know about any nested pushes yet. The lowest numbered
            // register we can use is r4.
            instruction_set_opt_int(ins, 0x84);
            continue;
        }

        // We otherwise only care about pops, and only as long as they are
        // paired with a push in the same basic block.
        if (opcode != OP_POP) {
            continue;
        }
        if (last_push == NULL) {
            continue;
        }

        // We've found a pop with a matching push that we can optimize.

        // Convert the push to a mov into the temporary register
        int reg = instruction_opt_int(last_push);
        instruction_set_arg1(last_push, instruction_arg0(last_push));
        instruction_set_arg0(last_push, reg);
        instruction_set_opcode(last_push, OP_MOV);

        // Convert the pop to a mov from the temporary register
        instruction_set_arg1(ins, reg);
        instruction_set_opcode(ins, OP_MOV);

        // We're done with the original push instruction
        last_push = instruction_opt_vp(last_push);

        // If we have an outer push instruction, bump the register it can use
        // (but only if it's not already larger)
        if (last_push) {
            int new_reg = (1 + reg);
            if (new_reg > 0x89) {
                // No free registers. We're not going to be able to pair up
                // anything else in our stack; just clear it.
                last_push = NULL;
                continue;
            }
            int old_reg = instruction_opt_int(last_push);
            if (new_reg > old_reg) {
                instruction_set_opt_int(last_push, new_reg);
            }
        }
    }
}



/*
 * Redundant load optimization
 *
 * (replace unnecessary ldw with mov)
 */

static void optimize_load(void) {
}



/*
 * Constant propagation
 */

static void optimize_propagate(void) {
}



/*
 * Leaf stack frame elimination
 *
 * Eliminates stack frames from branchless leaf functions that do not require
 * stack space.
 */

static void optimize_leaf(void) {
}



/*
 * Dead store elimination
 */

static void optimize_eliminate_dead_stores(void) {
}



// TODO: It would be better if each pass just allocated whatever memory it
// needs while it's running. libc/0 doesn't reclaim memory yet so for now we
// allocate all this up front.

static void optimize_setup(void) {
}

static void optimize_teardown(void) {
}

#endif
